project_id = "sxdraeptzuamsgjcvfeg"

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-quote]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = true

[functions.get-stripe-publishable-key]
verify_jwt = false
