// ─── Ops Assistant knowledge export ────────────────────────────────────────
//
//   npm run docs:export
//
// Writes a reviewable snapshot of the same chunks the live assistant loads
// from docs/admin-workspace/*.md on every request. The assistant does not
// wait on this file — regenerating a guide updates answers on the next
// request. This JSON exists so a guide change and the resulting knowledge
// are the same reviewable diff.

import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

import {
  buildKnowledgePack,
  isGuideFile,
  type ShotInput,
} from "../../src/lib/ops-assistant/guide-chunks";

const ROOT = resolve(__dirname, "../..");
const DOCS_DIR = join(ROOT, "docs/admin-workspace");
const SHOTS = join(DOCS_DIR, "screenshots/manifest.json");
const OUT = join(DOCS_DIR, "_data/ops-assistant-knowledge.generated.json");

function main() {
  const files = readdirSync(DOCS_DIR)
    .filter(isGuideFile)
    .map((name) => ({
      slug: name.replace(/\.md$/, ""),
      raw: readFileSync(join(DOCS_DIR, name), "utf8"),
    }));

  let shots: ShotInput[] = [];
  if (existsSync(SHOTS)) {
    const manifest = JSON.parse(readFileSync(SHOTS, "utf8")) as { shots?: ShotInput[] };
    shots = (manifest.shots || []).map((s) => ({
      id: s.id,
      doc: s.doc,
      caption: s.caption,
      callouts: s.callouts || [],
    }));
  }

  const pack = {
    _readme:
      "GENERATED by npm run docs:export from docs/admin-workspace/*.md. The live Ops Assistant loads these same files on each request, so the assistant and docs.novaracleaning.com stay one body of text. Do not edit by hand — change the guide and re-run.",
    ...buildKnowledgePack(files, shots),
  };

  writeFileSync(OUT, `${JSON.stringify(pack, null, 2)}\n`);

  const gates = pack.chunks.filter((c) => c.containsGate).length;
  const discrepancies = pack.chunks.filter((c) => c.containsDiscrepancy).length;
  console.log(`${pack.chunks.length} chunks from ${files.length} guides`);
  console.log(`  ${gates} contain a hard stop`);
  console.log(`  ${discrepancies} contain a known discrepancy`);
  console.log(`\nWrote ${OUT}`);
}

main();
