// ─── Walkthrough screen recordings ──────────────────────────────────────────
//
//   npm run tours:record                      # every clip
//   npm run tours:record -- pay-and-score     # one
//
// Requires the dev server on http://localhost:3100 (npm run dev -- --port 3100).
//
// What this does: opens the real contractor portal, opens the Help menu the
// way a contractor would, starts a walkthrough, and clicks through it while
// Playwright records the screen. The clip is therefore a recording of the
// actual walkthrough running on the actual UI — not a separate scripted
// re-enactment that can drift away from it. There is one source of truth for
// what these say, and it is src/lib/tours/catalog.ts.
//
// What it never does: touch real data. Every Supabase call and every one of
// our API routes is answered from scripts/tours/demo-contractor.ts (see
// mock.ts), so no real client, contractor or payout can appear in a clip.
// That applies even though the clips end up behind authentication.
//
// Captions come out as a WebVTT file per clip, with cue timings taken from
// when each step actually appeared rather than guessed. The clips are silent,
// so this is the only way the words are machine-readable — and burning text
// into the pixels would make it untranslatable and unsearchable.
//
// Output: docs/contractor-tours/recordings/<tour-id>.{webm,vtt} plus a
// manifest recording what was captured, when, and from which source files.
// Publishing to Supabase Storage is a separate step (tours:publish), so a
// recording run needs no credentials at all.

import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { chromium, type Browser, type Page } from "playwright";

import { TOURS, type Tour } from "../../src/lib/tours/catalog";
import { CHECKLIST_TOKEN, PHOTO_TOKEN } from "./demo-contractor";
import { BLOCKED_HOSTS, demoSession, handleApiRoute, handleSupabase } from "./mock";
import { REPO_ROOT, TOUR_SOURCES, hashSources } from "./sources";

const OUT_DIR = resolve(REPO_ROOT, "docs/contractor-tours/recordings");
// The manifest sits with the app rather than with the media: the training
// page and the admin panel both import it, and the video bytes are published
// to storage instead of being bundled.
const MANIFEST = resolve(REPO_ROOT, "src/lib/tours/recordings.manifest.json");
const BASE_URL = process.env.TOURS_RECORD_BASE_URL || "http://localhost:3100";

/** 720p. Legible on a phone, and small enough to sit in a storage bucket. */
const VIEWPORT = { width: 1280, height: 800 };

/**
 * The Supabase auth key supabase-js looks for in localStorage. Matches the
 * project ref in src/integrations/supabase/client.ts; the admin capture
 * harness injects the same key.
 */
const AUTH_STORAGE_KEY = "sb-sxdraeptzuamsgjcvfeg-auth-token";

/** Where each clip starts, so token-scoped steps land on the real screen. */
const START_URL: Record<string, string> = {
  "working-the-checklist": `/cleaner/job-checklist/${CHECKLIST_TOKEN}`,
  "photo-documentation": `/cleaner/job-photos/${PHOTO_TOKEN}`,
  "communication": `/cleaner/job-checklist/${CHECKLIST_TOKEN}`,
  "availability-and-offers": "/cleaner/job-offers",
};

/**
 * How long to hold a step on screen.
 *
 * These clips are silent, so the dwell is reading time, not narration time.
 * Bounded at both ends: under four seconds nobody finishes the sentence, and
 * over eight the clip stops feeling like it's going anywhere — and a viewer
 * who needs longer can pause, which a viewer bored into closing the tab
 * cannot.
 */
function dwellMs(text: string): number {
  const words = text.trim().split(/\s+/).length;
  return Math.min(8000, Math.max(4000, 3000 + words * 130));
}

function vttTimestamp(ms: number): string {
  const total = Math.max(0, ms);
  const hours = Math.floor(total / 3_600_000);
  const minutes = Math.floor((total % 3_600_000) / 60_000);
  const seconds = Math.floor((total % 60_000) / 1000);
  const millis = Math.floor(total % 1000);
  const pad = (n: number, width = 2) => String(n).padStart(width, "0");
  return `${pad(hours)}:${pad(minutes)}:${pad(seconds)}.${pad(millis, 3)}`;
}

interface Cue {
  startMs: number;
  endMs: number;
  text: string;
}

function buildVtt(tour: Tour, cues: Cue[]): string {
  const lines = ["WEBVTT", "", `NOTE ${tour.title} — generated by npm run tours:record`, ""];
  cues.forEach((cue, index) => {
    // Cue ends are padded so a caption doesn't vanish the instant the step
    // advances, which can push them past the next cue's start. Two cues on
    // screen at once is worse than one that's slightly short, so the next
    // cue wins the overlap.
    const next = cues[index + 1];
    const endMs = next ? Math.min(cue.endMs, next.startMs - 1) : cue.endMs;

    lines.push(String(index + 1));
    lines.push(`${vttTimestamp(cue.startMs)} --> ${vttTimestamp(Math.max(endMs, cue.startMs + 1))}`);
    // Hard-wrap so a caption renderer doesn't spread one cue across the
    // whole frame.
    lines.push(...wrap(cue.text, 72));
    lines.push("");
  });
  return `${lines.join("\n")}\n`;
}

function wrap(text: string, width: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if (line && `${line} ${word}`.length > width) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines;
}

async function newPage(browser: Browser, videoDir: string): Promise<Page> {
  const context = await browser.newContext({
    viewport: VIEWPORT,
    colorScheme: "light",
    recordVideo: { dir: videoDir, size: VIEWPORT },
  });

  await context.route("**/*.supabase.co/**", (route, request) => handleSupabase(route, request));
  await context.route("**/api/**", (route, request) => handleApiRoute(route, request));
  await context.route(BLOCKED_HOSTS, (route) => route.abort());

  await context.addInitScript(
    ([authKey, session, dismissKey]) => {
      window.localStorage.setItem(authKey as string, JSON.stringify(session));
      // Suppress the first-login auto-start. The clips open the Help menu
      // instead, which also shows contractors where to find these later —
      // and lets one run record one specific walkthrough.
      window.sessionStorage.setItem(dismissKey as string, "true");
    },
    [AUTH_STORAGE_KEY, demoSession(), "novara.tours.dismissed.v1"] as const,
  );

  return context.newPage();
}

interface Recorded {
  id: string;
  title: string;
  version: number;
  file: string;
  captionFile: string;
  startUrl: string;
  steps: number;
  durationSeconds: number;
  generatedAt: string;
  sourceHashes: Record<string, string | null>;
  problems: string[];
}

async function record(browser: Browser, tour: Tour): Promise<Recorded | null> {
  const videoDir = resolve(OUT_DIR, `.tmp-${tour.id}`);
  mkdirSync(videoDir, { recursive: true });

  const startUrl = START_URL[tour.id] || "/cleaner/dashboard";
  const problems: string[] = [];
  const cues: Cue[] = [];
  const page = await newPage(browser, videoDir);
  const t0 = Date.now();
  const elapsed = () => Date.now() - t0;

  try {
    await page.goto(`${BASE_URL}${startUrl}`, { waitUntil: "commit", timeout: 45_000 });
    await page.waitForLoadState("networkidle", { timeout: 20_000 }).catch(() => {});
    await page.waitForTimeout(1500);

    const leadInStart = elapsed();

    // Open the walkthrough the way a contractor does.
    const help = page.locator('[data-tour="help-button"]').first();
    await help.waitFor({ state: "visible", timeout: 20_000 });
    await help.click();

    const dialog = page.getByRole("dialog");
    await dialog.waitFor({ state: "visible", timeout: 10_000 });
    await page.waitForTimeout(1200);

    cues.push({
      startMs: leadInStart,
      endMs: elapsed() + 600,
      text: `Every walkthrough lives behind Help and training. Starting "${tour.title}".`,
    });

    // The launcher lists one row per walkthrough; click Start (or Replay) in
    // this walkthrough's row.
    const row = dialog.locator(`[data-tour-row="${tour.id}"]`).first();
    await row.waitFor({ state: "visible", timeout: 10_000 });
    const startButton = row.getByRole("button", { name: /Start|Replay/ }).first();
    await startButton.click();

    await page
      .getByRole("dialog", { name: new RegExp(`${escapeRegExp(tour.title)} — step`) })
      .waitFor({ state: "visible", timeout: 15_000 });

    // Walk the steps. The card's own text is on screen; the cue carries the
    // same words so the clip is captioned rather than just legible.
    for (let index = 0; index < tour.steps.length; index += 1) {
      const step = tour.steps[index];
      const startMs = elapsed();

      // Wait for the step to settle on its target before reading anything.
      // The card shows its `body` while the overlay is still hunting for the
      // element and only swaps to `fallback` once it gives up, so reading
      // immediately would caption half the steps with text the clip never
      // shows — and the swap is exactly the case worth getting right.
      await page
        .locator('[role="dialog"][data-tour-step-state]:not([data-tour-step-state="looking"])')
        .first()
        .waitFor({ state: "attached", timeout: 12_000 })
        .catch(() => {
          problems.push(`step ${index + 1} (${step.id}): never settled on a target`);
        });

      const shown = await page
        .locator('[role="dialog"] p[aria-live="polite"]')
        .first()
        .innerText()
        .catch(() => step.body);

      await page.waitForTimeout(dwellMs(shown));

      cues.push({
        startMs,
        endMs: elapsed(),
        text: `${step.title}. ${shown}`.replace(/\s+/g, " ").trim(),
      });

      const label = index === tour.steps.length - 1 ? "Done" : "Next";
      const button = page.getByRole("button", { name: label }).first();
      if ((await button.count()) === 0) {
        problems.push(`step ${index + 1} (${step.id}): no "${label}" button`);
        break;
      }
      await button.click();
      await page.waitForTimeout(700);
    }

    // Let the closing frame breathe so the clip doesn't cut mid-fade.
    await page.waitForTimeout(1200);
    const durationMs = elapsed();

    const video = page.video();
    await page.context().close(); // flushes the video file
    if (!video) {
      problems.push("playwright produced no video");
      return null;
    }

    const tempPath = await video.path();
    const file = `${tour.id}.webm`;
    renameSync(tempPath, resolve(OUT_DIR, file));
    rmSync(videoDir, { recursive: true, force: true });

    const captionFile = `${tour.id}.vtt`;
    writeFileSync(resolve(OUT_DIR, captionFile), buildVtt(tour, cues));

    return {
      id: tour.id,
      title: tour.title,
      version: tour.version,
      file,
      captionFile,
      startUrl,
      steps: tour.steps.length,
      durationSeconds: Math.round(durationMs / 1000),
      generatedAt: new Date().toISOString(),
      sourceHashes: hashSources(TOUR_SOURCES[tour.id] || []),
      problems,
    };
  } catch (err) {
    problems.push(`recording failed: ${err instanceof Error ? err.message : String(err)}`);
    await page.context().close().catch(() => {});
    rmSync(videoDir, { recursive: true, force: true });
    return {
      id: tour.id,
      title: tour.title,
      version: tour.version,
      file: "",
      captionFile: "",
      startUrl,
      steps: tour.steps.length,
      durationSeconds: 0,
      generatedAt: new Date().toISOString(),
      sourceHashes: {},
      problems,
    };
  }
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

async function main() {
  const filter = process.argv.slice(2).filter((a) => !a.startsWith("-"));
  const tours = filter.length ? TOURS.filter((t) => filter.includes(t.id)) : TOURS;

  if (!tours.length) {
    console.error(`No walkthrough matched ${filter.join(", ")}`);
    process.exit(1);
  }

  mkdirSync(OUT_DIR, { recursive: true });
  mkdirSync(resolve(MANIFEST, ".."), { recursive: true });

  // Fail loudly if the dev server isn't up. A run against a dead server would
  // produce seven clips of an error page, which is worse than no clips.
  try {
    const res = await fetch(`${BASE_URL}/cleaner/auth`);
    if (!res.ok) throw new Error(`status ${res.status}`);
  } catch (err) {
    console.error(
      `Cannot reach the dev server at ${BASE_URL} (${err instanceof Error ? err.message : err}).\n` +
        `Start it first:  npm run dev -- --port 3100`,
    );
    process.exit(1);
  }

  const browser = await chromium.launch();
  const results: Recorded[] = [];
  for (const tour of tours) {
    process.stdout.write(`  ${tour.id.padEnd(26)} `);
    const result = await record(browser, tour);
    if (!result || !result.file) console.log("FAILED");
    else console.log(`ok (${result.durationSeconds}s, ${result.steps} steps)`);
    if (result) results.push(result);
  }
  await browser.close();

  // Merge rather than replace: a filtered run must not drop the entries for
  // the clips it didn't touch, or the training page would start linking
  // recordings the manifest no longer knows about.
  let previous: Recorded[] = [];
  try {
    previous = JSON.parse(readFileSync(MANIFEST, "utf8")).recordings ?? [];
  } catch {
    previous = [];
  }
  const merged = new Map<string, Recorded>();
  for (const entry of previous) merged.set(entry.id, entry);
  for (const entry of results) if (entry.file) merged.set(entry.id, entry);

  const order = new Map(TOURS.map((t, i) => [t.id as string, i]));
  const recordings = [...merged.values()].sort(
    (a, b) => (order.get(a.id) ?? 999) - (order.get(b.id) ?? 999),
  );

  writeFileSync(
    MANIFEST,
    `${JSON.stringify(
      {
        _readme:
          "GENERATED by npm run tours:record. Captured against the real contractor portal with invented data only (scripts/tours/demo-contractor.ts) — the production database is never contacted. Re-record with the same command; this manifest, not the video files, is what tells you when a clip went stale.",
        generatedAt: new Date().toISOString(),
        baseUrl: BASE_URL,
        viewport: VIEWPORT,
        recordings,
      },
      null,
      2,
    )}\n`,
  );

  const failed = results.filter((r) => !r.file);
  console.log(`\n${results.length - failed.length}/${results.length} recorded → ${OUT_DIR}`);
  if (failed.length) {
    for (const f of failed) console.log(`  ${f.id}: ${f.problems.join("; ")}`);
    process.exitCode = 1;
  }
}

main();
