-- Add Maryland ZIP codes statewide
-- Using INSERT ... ON CONFLICT to avoid duplicates

INSERT INTO service_coverage_zones (zip_code, city, county, state, tier, tier_label, pricing_multiplier, is_active)
VALUES
-- Anne Arundel County (Annapolis area) - Tier 1 Affluent
('21401', 'Annapolis', 'Anne Arundel County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21402', 'Annapolis', 'Anne Arundel County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21403', 'Annapolis', 'Anne Arundel County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21404', 'Annapolis', 'Anne Arundel County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21405', 'Annapolis', 'Anne Arundel County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21409', 'Annapolis', 'Anne Arundel County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21012', 'Arnold', 'Anne Arundel County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21032', 'Crownsville', 'Anne Arundel County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21035', 'Davidsonville', 'Anne Arundel County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21037', 'Edgewater', 'Anne Arundel County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21054', 'Gambrills', 'Anne Arundel County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21060', 'Glen Burnie', 'Anne Arundel County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21061', 'Glen Burnie', 'Anne Arundel County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21062', 'Glen Burnie', 'Anne Arundel County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21076', 'Hanover', 'Anne Arundel County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21090', 'Linthicum Heights', 'Anne Arundel County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21108', 'Millersville', 'Anne Arundel County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21113', 'Odenton', 'Anne Arundel County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21114', 'Crofton', 'Anne Arundel County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21122', 'Pasadena', 'Anne Arundel County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21140', 'Riva', 'Anne Arundel County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21144', 'Severn', 'Anne Arundel County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21146', 'Severna Park', 'Anne Arundel County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21225', 'Brooklyn', 'Anne Arundel County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21226', 'Curtis Bay', 'Anne Arundel County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21240', 'BWI Airport', 'Anne Arundel County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),

-- Frederick County - Tier 2 Upper-Middle
('21701', 'Frederick', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21702', 'Frederick', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21703', 'Frederick', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21704', 'Frederick', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21705', 'Frederick', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21709', 'Frederick', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21710', 'Adamstown', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21714', 'Braddock Heights', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21716', 'Brunswick', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21717', 'Buckeystown', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21718', 'Burkittsville', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21719', 'Cascade', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21727', 'Emmitsburg', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21754', 'Ijamsville', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21755', 'Jefferson', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21757', 'Keymar', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21758', 'Knoxville', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21769', 'Middletown', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21770', 'Monrovia', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21773', 'Myersville', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21774', 'New Market', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21777', 'Point of Rocks', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21778', 'Rocky Ridge', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21780', 'Sabillasville', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21787', 'Taneytown', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21788', 'Thurmont', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21790', 'Tuscarora', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21791', 'Union Bridge', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21793', 'Walkersville', 'Frederick County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21798', 'Woodsboro', 'Frederick County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),

-- Harford County (Bel Air area) - Tier 2 Upper-Middle
('21001', 'Aberdeen', 'Harford County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21005', 'Aberdeen Proving Ground', 'Harford County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21009', 'Abingdon', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21010', 'Gunpowder', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21014', 'Bel Air', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21015', 'Bel Air', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21017', 'Belcamp', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21028', 'Churchville', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21034', 'Darlington', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21040', 'Edgewood', 'Harford County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21047', 'Fallston', 'Harford County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21050', 'Forest Hill', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21078', 'Havre de Grace', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21084', 'Jarrettsville', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21085', 'Joppa', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21130', 'Perryman', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21132', 'Pylesville', 'Harford County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21154', 'Street', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21160', 'Whiteford', 'Harford County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21161', 'White Hall', 'Harford County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),

-- Carroll County (Westminster) - Tier 2 Upper-Middle
('21048', 'Finksburg', 'Carroll County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21074', 'Hampstead', 'Carroll County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21102', 'Manchester', 'Carroll County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21104', 'Marriottsville', 'Carroll County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21136', 'Reisterstown', 'Carroll County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21155', 'Upperco', 'Carroll County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21157', 'Westminster', 'Carroll County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21158', 'Westminster', 'Carroll County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21776', 'New Windsor', 'Carroll County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21784', 'Sykesville', 'Carroll County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21787', 'Taneytown', 'Carroll County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21797', 'Woodbine', 'Carroll County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),

-- Charles County (Waldorf area) - Tier 2/3
('20601', 'Waldorf', 'Charles County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20602', 'Waldorf', 'Charles County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20603', 'Waldorf', 'Charles County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20611', 'Bel Alton', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20612', 'Benedict', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20616', 'Bryans Road', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20617', 'Bryantown', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20620', 'Bushwood', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20625', 'Cobb Island', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20632', 'Faulkner', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20640', 'Indian Head', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20645', 'Issue', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20646', 'La Plata', 'Charles County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20658', 'Marbury', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20664', 'Nanjemoy', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20675', 'Pomfret', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20677', 'Port Tobacco', 'Charles County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20695', 'White Plains', 'Charles County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),

-- Calvert County - Tier 2 Upper-Middle
('20610', 'Barstow', 'Calvert County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20615', 'Broomes Island', 'Calvert County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20629', 'Dowell', 'Calvert County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20639', 'Huntingtown', 'Calvert County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20657', 'Lusby', 'Calvert County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20676', 'Port Republic', 'Calvert County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20678', 'Prince Frederick', 'Calvert County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20685', 'Saint Leonard', 'Calvert County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20688', 'Solomons', 'Calvert County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('20714', 'North Beach', 'Calvert County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20732', 'Chesapeake Beach', 'Calvert County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20736', 'Owings', 'Calvert County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),

-- St. Mary''s County (Lexington Park) - Tier 3 Working/Middle
('20606', 'Abell', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20618', 'Bushwood', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20619', 'California', 'St. Marys County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20620', 'Callaway', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20621', 'Chaptico', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20622', 'Charlotte Hall', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20624', 'Clements', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20626', 'Coltons Point', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20628', 'Dameron', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20630', 'Drayden', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20634', 'Great Mills', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20636', 'Hollywood', 'St. Marys County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20650', 'Leonardtown', 'St. Marys County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20653', 'Lexington Park', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20659', 'Mechanicsville', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20667', 'Park Hall', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20670', 'Patuxent River', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20674', 'Piney Point', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20680', 'Ridge', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20684', 'Saint Inigoes', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20686', 'Saint Marys City', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20687', 'Scotland', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('20690', 'Tall Timbers', 'St. Marys County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('20692', 'Valley Lee', 'St. Marys County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),

-- Washington County (Hagerstown) - Tier 3 Working/Middle
('21711', 'Big Pool', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21713', 'Boonsboro', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21715', 'Brownsville', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21719', 'Cascade', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21720', 'Cavetown', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21722', 'Clear Spring', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21733', 'Fairplay', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21734', 'Funkstown', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21740', 'Hagerstown', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21741', 'Hagerstown', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21742', 'Hagerstown', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21746', 'Hagerstown', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21749', 'Hagerstown', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21750', 'Hancock', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21756', 'Keedysville', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21767', 'Maugansville', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21779', 'Rohrersville', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21781', 'Saint James', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21782', 'Sharpsburg', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21783', 'Smithsburg', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21795', 'Williamsport', 'Washington County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),

-- Allegany County (Cumberland) - Tier 3 Working/Middle
('21502', 'Cumberland', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21503', 'Cumberland', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21504', 'Cumberland', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21505', 'Cumberland', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21520', 'Accident', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21521', 'Barton', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21524', 'Corriganville', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21530', 'Flintstone', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21532', 'Frostburg', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21539', 'Lonaconing', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21540', 'Luke', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21543', 'Midland', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21545', 'Mount Savage', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21555', 'Oldtown', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21557', 'Rawlings', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21562', 'Westernport', 'Allegany County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),

-- Wicomico County (Salisbury) - Tier 3 Working/Middle
('21801', 'Salisbury', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21802', 'Salisbury', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21803', 'Salisbury', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21804', 'Salisbury', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21810', 'Allen', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21817', 'Crisfield', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21822', 'Eden', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21826', 'Fruitland', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21830', 'Hebron', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21837', 'Mardela Springs', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21849', 'Parsonsburg', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21850', 'Pittsville', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21856', 'Quantico', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21861', 'Sharptown', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21874', 'Willards', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21875', 'Delmar', 'Wicomico County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),

-- Worcester County (Ocean City) - Tier 1/2 (Resort Area)
('21811', 'Berlin', 'Worcester County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21813', 'Bishopville', 'Worcester County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21842', 'Ocean City', 'Worcester County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21843', 'Ocean City', 'Worcester County', 'MD', 'tier_1', 'Affluent', 1.10, true),
('21851', 'Pocomoke City', 'Worcester County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21862', 'Showell', 'Worcester County', 'MD', 'tier_2', 'Upper-Middle', 1.05, true),
('21863', 'Snow Hill', 'Worcester County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21864', 'Stockton', 'Worcester County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21869', 'Vienna', 'Worcester County', 'MD', 'tier_3', 'Working/Middle', 1.00, true),
('21872', 'Whaleyville', 'Worcester County', 'MD', 'tier_3', 'Working/Middle', 1.00, true)

ON CONFLICT (zip_code) DO NOTHING;