-- ─── QC & Job Documentation Hub ──────────────────────────────────────────────
--
-- Two connected capabilities:
--   1. Every completed job gets a durable documentation record (before/after
--      photos, checklist snapshot, notes, timestamps). Supabase is the source
--      of truth; each job is mirrored asynchronously to a structured Google
--      Drive folder with a generated completion-summary PDF (the dispute
--      packet). Photos live in Supabase for 14 days, then are purged — but
--      ONLY after the Drive mirror is confirmed.
--   2. QC issues (complaints, re-cleans, damage, no-shows, quality flags…)
--      are always tied to a job, carrying that job's documentation as
--      evidence, with a full lifecycle + audit trail. High/Critical issues
--      alert admin immediately through the existing Discord event routing.
--
-- Reuses: public.events + discord_routes (alerts), pg_cron + pg_net (workers),
-- is_admin_or_va() RLS, cleaner-job-photos bucket, job_checklists.

-- ─── 1. job_documentation — one durable record per completed booking ────────
CREATE TABLE IF NOT EXISTS public.job_documentation (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE REFERENCES public.bookings(id) ON DELETE CASCADE,
  job_id uuid,
  booking_ref text,
  client_name text,
  client_email text,
  service_type text,
  service_date date,
  address text,
  cleaner_names text,
  -- Snapshot of photo URLs at documentation time (source: bookings arrays).
  before_photos jsonb NOT NULL DEFAULT '[]'::jsonb,
  after_photos jsonb NOT NULL DEFAULT '[]'::jsonb,
  photo_count integer NOT NULL DEFAULT 0,
  -- Checklist snapshot captured by the mirror worker at documentation time.
  checklist_snapshot jsonb,
  checklist_progress_pct integer,
  notes text,
  completed_at timestamptz,
  -- "Documented" = has both before AND after photos. The compliance metric.
  documented boolean NOT NULL DEFAULT false,
  -- Google Drive mirror state machine. pending → mirroring → mirrored.
  -- Failures retry with backoff; photos are NEVER purged unless mirrored.
  mirror_status text NOT NULL DEFAULT 'pending'
    CHECK (mirror_status IN ('pending','mirroring','mirrored','failed','skipped')),
  mirror_attempts integer NOT NULL DEFAULT 0,
  mirror_last_error text,
  mirror_next_attempt_at timestamptz,
  mirrored_at timestamptz,
  drive_folder_id text,
  drive_folder_url text,
  drive_pdf_id text,
  drive_pdf_url text,
  drive_file_count integer NOT NULL DEFAULT 0,
  -- 14-day retention: set when Supabase copies were deleted (Drive keeps all).
  photos_purged_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS job_documentation_mirror_idx
  ON public.job_documentation (mirror_status, mirror_next_attempt_at);
CREATE INDEX IF NOT EXISTS job_documentation_purge_idx
  ON public.job_documentation (mirror_status, completed_at)
  WHERE photos_purged_at IS NULL;
CREATE INDEX IF NOT EXISTS job_documentation_booking_idx
  ON public.job_documentation (booking_id);
ALTER TABLE public.job_documentation ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='job_documentation' AND policyname='job_documentation_admin_all') THEN
    CREATE POLICY job_documentation_admin_all ON public.job_documentation FOR ALL TO authenticated
      USING (public.is_admin_or_va(auth.uid())) WITH CHECK (public.is_admin_or_va(auth.uid()));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='job_documentation' AND policyname='job_documentation_service_role') THEN
    CREATE POLICY job_documentation_service_role ON public.job_documentation FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END$$;

-- ─── 2. qc_issues — every issue is tied to a job ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.qc_issues (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  issue_number integer GENERATED BY DEFAULT AS IDENTITY,
  booking_id uuid NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
  job_id uuid,
  documentation_id uuid REFERENCES public.job_documentation(id) ON DELETE SET NULL,
  cleaner_id uuid,
  cleaner_name text,
  client_name text,
  client_email text,
  booking_ref text,
  issue_type text NOT NULL DEFAULT 'complaint'
    CHECK (issue_type IN ('complaint','reclean','damage','no_show','late','quality_flag','payment','other')),
  severity text NOT NULL DEFAULT 'medium'
    CHECK (severity IN ('low','medium','high','critical')),
  status text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open','investigating','awaiting_customer','resolved','escalated')),
  title text NOT NULL,
  description text,
  reported_via text NOT NULL DEFAULT 'va'
    CHECK (reported_via IN ('va','admin','cleaner_field','system')),
  reported_by uuid,
  reported_by_name text,
  resolution_note text,
  resolution_photos jsonb NOT NULL DEFAULT '[]'::jsonb,
  resolved_at timestamptz,
  resolved_by uuid,
  resolved_by_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS qc_issues_status_idx ON public.qc_issues (status, severity, created_at DESC);
CREATE INDEX IF NOT EXISTS qc_issues_booking_idx ON public.qc_issues (booking_id);
CREATE INDEX IF NOT EXISTS qc_issues_cleaner_idx ON public.qc_issues (cleaner_id, created_at DESC);
ALTER TABLE public.qc_issues ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='qc_issues' AND policyname='qc_issues_admin_all') THEN
    CREATE POLICY qc_issues_admin_all ON public.qc_issues FOR ALL TO authenticated
      USING (public.is_admin_or_va(auth.uid())) WITH CHECK (public.is_admin_or_va(auth.uid()));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='qc_issues' AND policyname='qc_issues_service_role') THEN
    CREATE POLICY qc_issues_service_role ON public.qc_issues FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END$$;

-- ─── 3. qc_issue_events — full audit trail (who / what / when) ───────────────
CREATE TABLE IF NOT EXISTS public.qc_issue_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  issue_id uuid NOT NULL REFERENCES public.qc_issues(id) ON DELETE CASCADE,
  action text NOT NULL
    CHECK (action IN ('created','status_change','note','updated','resolved','escalated')),
  from_status text,
  to_status text,
  note text,
  actor_id uuid,
  actor_name text,
  data jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS qc_issue_events_issue_idx ON public.qc_issue_events (issue_id, created_at);
ALTER TABLE public.qc_issue_events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='qc_issue_events' AND policyname='qc_issue_events_admin_read') THEN
    CREATE POLICY qc_issue_events_admin_read ON public.qc_issue_events FOR SELECT TO authenticated
      USING (public.is_admin_or_va(auth.uid()));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='qc_issue_events' AND policyname='qc_issue_events_service_role') THEN
    CREATE POLICY qc_issue_events_service_role ON public.qc_issue_events FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END$$;

-- ─── 4. Auto-create documentation record when a booking completes ────────────
-- Fires on completion AND on later photo submissions (photos often land after
-- the status flip). Never overwrites a purged record's photo arrays.
CREATE OR REPLACE FUNCTION public.ensure_job_documentation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_before jsonb;
  v_after jsonb;
  v_documented boolean;
BEGIN
  IF NEW.status IS DISTINCT FROM 'completed' THEN RETURN NEW; END IF;

  v_before := to_jsonb(coalesce(NEW.before_photos, '{}'::text[]));
  v_after  := to_jsonb(coalesce(NEW.after_photos,  '{}'::text[]));
  v_documented := jsonb_array_length(v_before) > 0 AND jsonb_array_length(v_after) > 0;

  INSERT INTO public.job_documentation (
    booking_id, job_id, booking_ref, client_name, client_email,
    service_type, service_date, address, before_photos, after_photos,
    photo_count, notes, completed_at, documented
  ) VALUES (
    NEW.id,
    NEW.job_id,
    CASE WHEN NEW.booking_number IS NOT NULL THEN 'NOV-' || lpad(NEW.booking_number::text, 5, '0') ELSE NULL END,
    nullif(btrim(coalesce(NEW.first_name,'') || ' ' || coalesce(NEW.last_name,'')), ''),
    NEW.email,
    NEW.service_type,
    NEW.service_date,
    nullif(btrim(concat_ws(', ', NEW.address, NEW.city, NEW.state) || ' ' || coalesce(NEW.zip_code,'')), ''),
    v_before,
    v_after,
    jsonb_array_length(v_before) + jsonb_array_length(v_after),
    nullif(btrim(concat_ws(E'\n', NEW.team_notes, NEW.issues_notes)), ''),
    coalesce(NEW.completed_at, now()),
    v_documented
  )
  ON CONFLICT (booking_id) DO UPDATE SET
    job_id        = coalesce(EXCLUDED.job_id, job_documentation.job_id),
    before_photos = CASE WHEN job_documentation.photos_purged_at IS NULL THEN EXCLUDED.before_photos ELSE job_documentation.before_photos END,
    after_photos  = CASE WHEN job_documentation.photos_purged_at IS NULL THEN EXCLUDED.after_photos  ELSE job_documentation.after_photos  END,
    photo_count   = CASE WHEN job_documentation.photos_purged_at IS NULL THEN EXCLUDED.photo_count   ELSE job_documentation.photo_count   END,
    documented    = CASE WHEN job_documentation.photos_purged_at IS NULL THEN EXCLUDED.documented    ELSE job_documentation.documented    END,
    notes         = coalesce(EXCLUDED.notes, job_documentation.notes),
    completed_at  = coalesce(job_documentation.completed_at, EXCLUDED.completed_at),
    -- New photos after a successful mirror → re-queue (worker dedupes by filename).
    mirror_status = CASE
      WHEN job_documentation.photos_purged_at IS NOT NULL THEN job_documentation.mirror_status
      WHEN job_documentation.mirror_status = 'mirrored'
        AND EXCLUDED.photo_count > job_documentation.photo_count THEN 'pending'
      ELSE job_documentation.mirror_status
    END,
    updated_at    = now();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ensure_job_documentation ON public.bookings;
CREATE TRIGGER trg_ensure_job_documentation
  AFTER INSERT OR UPDATE OF status, before_photos, after_photos ON public.bookings
  FOR EACH ROW EXECUTE FUNCTION public.ensure_job_documentation();

-- ─── 5. Backfill: completed bookings from the last 90 days ───────────────────
INSERT INTO public.job_documentation (
  booking_id, job_id, booking_ref, client_name, client_email, service_type,
  service_date, address, before_photos, after_photos, photo_count, notes,
  completed_at, documented
)
SELECT
  b.id, b.job_id,
  CASE WHEN b.booking_number IS NOT NULL THEN 'NOV-' || lpad(b.booking_number::text, 5, '0') END,
  nullif(btrim(coalesce(b.first_name,'') || ' ' || coalesce(b.last_name,'')), ''),
  b.email, b.service_type, b.service_date,
  nullif(btrim(concat_ws(', ', b.address, b.city, b.state) || ' ' || coalesce(b.zip_code,'')), ''),
  to_jsonb(coalesce(b.before_photos, '{}'::text[])),
  to_jsonb(coalesce(b.after_photos,  '{}'::text[])),
  coalesce(array_length(b.before_photos, 1), 0) + coalesce(array_length(b.after_photos, 1), 0),
  nullif(btrim(concat_ws(E'\n', b.team_notes, b.issues_notes)), ''),
  coalesce(b.completed_at, b.service_date::timestamptz),
  coalesce(array_length(b.before_photos, 1), 0) > 0 AND coalesce(array_length(b.after_photos, 1), 0) > 0
FROM public.bookings b
WHERE b.status = 'completed'
  AND coalesce(b.completed_at, b.service_date::timestamptz) > now() - interval '90 days'
ON CONFLICT (booking_id) DO NOTHING;

-- ─── 6. Discord alert routing for QC events ──────────────────────────────────
-- Unknown event types fall through notify_discord_on_event()'s ELSE branch
-- (generic bell + event summary), so routes alone are enough to wire alerts.
INSERT INTO public.discord_routes (event_type, webhook_key, role_keys) VALUES
  ('qc.issue.created',         'DISCORD_WEBHOOK_FLAG', ARRAY['DISCORD_ROLE_OPERATIONS','DISCORD_ROLE_RETENTION']),
  ('qc.issue.escalated',       'DISCORD_WEBHOOK_FLAG', ARRAY['DISCORD_ROLE_OPERATIONS','DISCORD_ROLE_RETENTION']),
  ('qc.documentation.failed',  'DISCORD_WEBHOOK_FLAG', ARRAY['DISCORD_ROLE_OPERATIONS'])
ON CONFLICT (event_type) DO UPDATE
  SET webhook_key = EXCLUDED.webhook_key, role_keys = EXCLUDED.role_keys, enabled = true;

-- ─── 7. Secret slot for the Drive root folder ────────────────────────────────
INSERT INTO public.app_secrets (key, value, description) VALUES
  ('GDRIVE_QC_ROOT_FOLDER_ID', '',
   'Google Drive folder id that roots the QC job-documentation archive (folders per year/month/job). The Google service account must have edit access to it.')
ON CONFLICT (key) DO NOTHING;

-- ─── 8. Cron: Drive mirror worker + 14-day retention purge ───────────────────
DO $$
DECLARE
  v_job_id bigint;
  v_supabase_url text;
  v_service_role text;
BEGIN
  SELECT value INTO v_supabase_url FROM public.app_secrets WHERE key = 'SUPABASE_URL';
  IF v_supabase_url IS NULL OR length(v_supabase_url) = 0 THEN
    v_supabase_url := 'https://sxdraeptzuamsgjcvfeg.supabase.co';
  END IF;
  SELECT value INTO v_service_role FROM public.app_secrets WHERE key = 'SUPABASE_SERVICE_ROLE_KEY';

  SELECT jobid INTO v_job_id FROM cron.job WHERE jobname = 'qc-drive-mirror';
  IF v_job_id IS NOT NULL THEN PERFORM cron.unschedule('qc-drive-mirror'); END IF;
  PERFORM cron.schedule(
    'qc-drive-mirror',
    '*/10 * * * *',
    format(
      $cron$
        SELECT net.http_post(
          url := '%s/functions/v1/qc-drive-mirror',
          headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'Authorization', 'Bearer ' || coalesce(%L::text, '')
          ),
          body := jsonb_build_object('source', 'pg_cron')
        );
      $cron$,
      v_supabase_url,
      v_service_role
    )
  );

  SELECT jobid INTO v_job_id FROM cron.job WHERE jobname = 'qc-retention-purge';
  IF v_job_id IS NOT NULL THEN PERFORM cron.unschedule('qc-retention-purge'); END IF;
  PERFORM cron.schedule(
    'qc-retention-purge',
    '30 8 * * *',
    format(
      $cron$
        SELECT net.http_post(
          url := '%s/functions/v1/qc-retention-purge',
          headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'Authorization', 'Bearer ' || coalesce(%L::text, '')
          ),
          body := jsonb_build_object('source', 'pg_cron')
        );
      $cron$,
      v_supabase_url,
      v_service_role
    )
  );
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping QC cron scheduling: %', SQLERRM;
END $$;
