-- ─── Cleaner Accountability System ───────────────────────────────────────────
--
-- Formal, documented escalation ladder tied to QC cases:
--   coaching note → strike → suspension (new assignments only) → removal.
--
-- Principles enforced by this schema + the cleaner-accountability edge fn:
--   * Every action requires a linked QC case OR a documented reason + note.
--   * NOTHING here touches pay for completed work — suspension blocks NEW
--     assignments only (via cleaners.status='suspended', which every dispatch
--     path already filters out); removal reuses the terminated offboarding
--     semantics and payouts owed still settle per the normal cycle.
--   * History is permanent: actions are never hard-deleted; expired strikes
--     stay in the ledger with status='expired'.
--   * Every formal email is archived on its action row (subject + body).
--
-- Reuses: qc_issues (case links), events + discord_routes (alerts),
-- app_settings (strike-expiry config), pg_cron + pg_net (auto-restore sweep),
-- is_admin_or_va() RLS.

-- ─── 1. cleaner_accountability_actions — the permanent ledger ────────────────
CREATE TABLE IF NOT EXISTS public.cleaner_accountability_actions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  action_number integer GENERATED BY DEFAULT AS IDENTITY,
  cleaner_id uuid NOT NULL REFERENCES public.cleaners(id) ON DELETE CASCADE,
  action_type text NOT NULL
    CHECK (action_type IN ('coaching_note','strike','suspension','removal')),
  -- Strike ladder position at issue time (Strike 1, 2, …). NULL for others.
  strike_number integer,
  -- The QC case that triggered the action (optional when a documented
  -- reason is supplied instead — enforced in the edge function).
  qc_issue_id uuid REFERENCES public.qc_issues(id) ON DELETE SET NULL,
  qc_issue_ref text,
  -- Documented reason (incident summary) + the admin's note. Both required.
  reason text NOT NULL,
  note text NOT NULL,
  -- Direct-to-suspend/remove below the normal ladder requires an explicit
  -- severe-cause acknowledgement (the reason doubles as its documentation).
  severe_cause boolean NOT NULL DEFAULT false,
  -- Suspension window (dates, inclusive) + how existing accepted jobs were
  -- handled ('keep' or 'reassign').
  suspension_start date,
  suspension_end date,
  existing_jobs_handling text
    CHECK (existing_jobs_handling IN ('keep','reassign')),
  -- Lifecycle: active → expired (strikes aging out) / completed (suspension
  -- window ended) / lifted (admin manually ended it early). Coaching notes
  -- and removals stay 'active' (they are point-in-time records).
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active','expired','completed','lifted')),
  expires_at timestamptz,          -- strike expiry (from accountability settings)
  expired_at timestamptz,
  completed_at timestamptz,        -- suspension window ended naturally
  lifted_at timestamptz,
  lifted_by uuid,
  lifted_by_name text,
  lift_note text,
  -- The formal email, archived verbatim as sent (admin-editable pre-send).
  email_to text,
  email_subject text,
  email_body text,
  email_sent boolean NOT NULL DEFAULT false,
  email_sent_at timestamptz,
  email_error text,
  email_skipped boolean NOT NULL DEFAULT false,
  -- Who took the action, and when.
  created_by uuid,
  created_by_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS caa_cleaner_idx
  ON public.cleaner_accountability_actions (cleaner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS caa_type_status_idx
  ON public.cleaner_accountability_actions (action_type, status);
CREATE INDEX IF NOT EXISTS caa_qc_issue_idx
  ON public.cleaner_accountability_actions (qc_issue_id);
ALTER TABLE public.cleaner_accountability_actions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='cleaner_accountability_actions' AND policyname='caa_admin_read') THEN
    -- Admin/VA read directly; ALL writes go through the edge function
    -- (service role) so every mutation is validated + logged.
    CREATE POLICY caa_admin_read ON public.cleaner_accountability_actions FOR SELECT TO authenticated
      USING (public.is_admin_or_va(auth.uid()));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='cleaner_accountability_actions' AND policyname='caa_service_role') THEN
    CREATE POLICY caa_service_role ON public.cleaner_accountability_actions FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END$$;

-- ─── 2. cleaners — suspension state + active strike counter ─────────────────
-- status='suspended' is the dispatch lever: dispatch-job, broadcast,
-- admin-booking-assign, and auto-dispatch all filter status='active', so a
-- suspended cleaner receives ZERO new offers without touching those paths.
ALTER TABLE public.cleaners ADD COLUMN IF NOT EXISTS active_strike_count integer NOT NULL DEFAULT 0;
ALTER TABLE public.cleaners ADD COLUMN IF NOT EXISTS suspended_at timestamptz;
ALTER TABLE public.cleaners ADD COLUMN IF NOT EXISTS suspended_until timestamptz;
ALTER TABLE public.cleaners ADD COLUMN IF NOT EXISTS suspension_reason text;

CREATE INDEX IF NOT EXISTS cleaners_suspended_until_idx
  ON public.cleaners (suspended_until)
  WHERE suspended_until IS NOT NULL;

-- ─── 3. Accountability settings (admin-configurable strike expiry) ──────────
-- strike_expiry_months = 0 disables expiry (strikes never age out).
INSERT INTO public.app_settings (key, value, description)
VALUES (
  'accountability_settings',
  '{"strike_expiry_months": 6}'::jsonb,
  'Cleaner accountability config. strike_expiry_months: months of clean performance after which a strike ages out of the active ladder (0 = never). Expired strikes remain in history.'
)
ON CONFLICT (key) DO NOTHING;

-- ─── 4. Discord alert routing for accountability events ─────────────────────
INSERT INTO public.discord_routes (event_type, webhook_key, role_keys) VALUES
  ('cleaner.strike_issued',        'DISCORD_WEBHOOK_FLAG', ARRAY['DISCORD_ROLE_OPERATIONS']),
  ('cleaner.suspended',            'DISCORD_WEBHOOK_FLAG', ARRAY['DISCORD_ROLE_OPERATIONS']),
  ('cleaner.suspension_ended',     'DISCORD_WEBHOOK_FLAG', ARRAY['DISCORD_ROLE_OPERATIONS']),
  ('cleaner.removed',              'DISCORD_WEBHOOK_FLAG', ARRAY['DISCORD_ROLE_OPERATIONS'])
ON CONFLICT (event_type) DO UPDATE
  SET webhook_key = EXCLUDED.webhook_key, role_keys = EXCLUDED.role_keys, enabled = true;

-- ─── 5. Cron: hourly sweep — auto-restore ended suspensions + expire strikes ─
DO $$
DECLARE
  v_job_id bigint;
  v_supabase_url text;
  v_service_role text;
BEGIN
  SELECT value INTO v_supabase_url FROM public.app_secrets WHERE key = 'SUPABASE_URL';
  IF v_supabase_url IS NULL OR length(v_supabase_url) = 0 THEN
    v_supabase_url := 'https://sxdraeptzuamsgjcvfeg.supabase.co';
  END IF;
  SELECT value INTO v_service_role FROM public.app_secrets WHERE key = 'SUPABASE_SERVICE_ROLE_KEY';

  SELECT jobid INTO v_job_id FROM cron.job WHERE jobname = 'cleaner-accountability-sweep';
  IF v_job_id IS NOT NULL THEN PERFORM cron.unschedule('cleaner-accountability-sweep'); END IF;
  PERFORM cron.schedule(
    'cleaner-accountability-sweep',
    '5 * * * *',
    format(
      $cron$
        SELECT net.http_post(
          url := '%s/functions/v1/cleaner-accountability',
          headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'Authorization', 'Bearer ' || coalesce(%L::text, '')
          ),
          body := jsonb_build_object('action', 'sweep', 'source', 'pg_cron')
        );
      $cron$,
      v_supabase_url,
      v_service_role
    )
  );
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping cleaner-accountability cron scheduling: %', SQLERRM;
END $$;
