-- ─── Model control ──────────────────────────────────────────────────────
--
-- Which model answers is configuration, not code. Three tiers:
--
--   default    general assistant traffic
--   strongest  analysis where a confident-wrong answer is expensive — report
--              insights, checklist feedback insights, money-adjacent questions
--   fallback   what runs when the strongest tier is unavailable, so a provider
--              outage degrades the answer rather than dropping the request
--
-- Editing these values takes effect on the next request. No redeploy.
--
-- NO API KEY IS STORED HERE. Keys are resolved by NAME (ANTHROPIC_API_KEY /
-- OPENAI_API_KEY) from the secrets manager at call time.

-- Provider seeds from the existing LLM_PROVIDER secret when one is set, so a
-- deployment already running OpenAI is not silently flipped to Anthropic by
-- this migration. Model IDs still seed to the Anthropic tiers below; an
-- OpenAI deployment sets its own in Admin → AI Models.
INSERT INTO public.app_settings (key, value, description)
VALUES (
  'model_control_settings',
  jsonb_build_object(
    'provider', COALESCE(
      NULLIF(lower(trim((SELECT value FROM public.app_secrets WHERE key = 'LLM_PROVIDER'))), ''),
      'anthropic'
    ),
    'tiers', jsonb_build_object(
      'default', 'claude-sonnet-5',
      'strongest', 'claude-opus-5',
      'fallback', 'claude-sonnet-5'
    ),
    -- An assistant question containing any of these routes to the strongest
    -- tier. A wrong price or pay figure gets quoted to a customer or a
    -- contractor, so a slow right answer beats a fast plausible one.
    'money_adjacent_intents', jsonb_build_array(
      'pricing', 'quote', 'pay', 'payout', 'payroll',
      'refund', 'invoice', 'billing', 'discount', 'credit'
    ),
    'timeout_ms', 60000,
    'max_tokens', 3000
  ),
  'Model routing by tier. default = general assistant, strongest = report and checklist insight generation plus money-adjacent assistant questions, fallback = degraded path when the strongest tier is unavailable. Admin-editable; changes apply on the next request with no redeploy. API keys are NOT stored here — they are resolved by name from the secrets manager.'
)
ON CONFLICT (key) DO NOTHING;

-- ─── Config history ─────────────────────────────────────────────────────
--
-- "Which model wrote this in March?" needs the config as it stood in March,
-- not the config as it stands today.

CREATE TABLE IF NOT EXISTS public.model_control_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version integer GENERATED BY DEFAULT AS IDENTITY,
  settings jsonb NOT NULL,
  previous_settings jsonb,
  change_summary text,
  changed_by uuid,
  changed_by_name text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS model_control_versions_created_idx
  ON public.model_control_versions (created_at DESC);

-- ─── Invocation log ─────────────────────────────────────────────────────
--
-- Every AI response records the model that actually produced it. Not the model
-- we asked for — `resolved_model` is what the provider reports, which is how a
-- silent alias change or a fallback becomes visible instead of invisible.

CREATE TABLE IF NOT EXISTS public.ai_model_invocations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Calling surface: weekly-report, checklist-feedback, admin-chat-agent.
  surface text NOT NULL,
  intent text,
  provider text NOT NULL,
  requested_tier text NOT NULL CHECK (requested_tier IN ('default','strongest','fallback')),
  served_tier text NOT NULL CHECK (served_tier IN ('default','strongest','fallback')),
  requested_model text,
  served_model text,
  resolved_model text,
  fell_back boolean NOT NULL DEFAULT false,
  fallback_reason text,
  latency_ms integer,
  ok boolean NOT NULL DEFAULT true,
  error text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ai_model_invocations_created_idx
  ON public.ai_model_invocations (created_at DESC);
CREATE INDEX IF NOT EXISTS ai_model_invocations_surface_idx
  ON public.ai_model_invocations (surface, created_at DESC);
-- Fallbacks are the ones worth finding fast: they mean a tier was down.
CREATE INDEX IF NOT EXISTS ai_model_invocations_fallback_idx
  ON public.ai_model_invocations (created_at DESC) WHERE fell_back = true;
CREATE INDEX IF NOT EXISTS ai_model_invocations_failed_idx
  ON public.ai_model_invocations (created_at DESC) WHERE ok = false;

COMMENT ON COLUMN public.ai_model_invocations.resolved_model IS
  'The model string the provider reported for this response. Differs from served_model when a provider alias resolves to a dated snapshot — this is the field that answers "what actually wrote this?".';

ALTER TABLE public.model_control_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_model_invocations ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['model_control_versions', 'ai_model_invocations'] LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE tablename = t AND policyname = t || '_admin_read'
    ) THEN
      EXECUTE format(
        'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (public.is_admin_or_va(auth.uid()))',
        t || '_admin_read', t
      );
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE tablename = t AND policyname = t || '_service_role'
    ) THEN
      EXECUTE format(
        'CREATE POLICY %I ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)',
        t || '_service_role', t
      );
    END IF;
  END LOOP;
END$$;

-- Retention: the log is an audit trail, not a data warehouse. A year is well
-- past any dispute window that would need it.
CREATE OR REPLACE FUNCTION public.purge_ai_model_invocations()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_deleted integer;
BEGIN
  DELETE FROM public.ai_model_invocations
   WHERE created_at < now() - interval '365 days';
  GET DIAGNOSTICS v_deleted = ROW_COUNT;
  RETURN v_deleted;
END;
$$;

DO $$
DECLARE
  v_job_id bigint;
BEGIN
  SELECT jobid INTO v_job_id FROM cron.job WHERE jobname = 'ai-model-invocations-purge';
  IF v_job_id IS NOT NULL THEN PERFORM cron.unschedule('ai-model-invocations-purge'); END IF;
  PERFORM cron.schedule(
    'ai-model-invocations-purge',
    '30 4 * * 0',
    $cron$ SELECT public.purge_ai_model_invocations(); $cron$
  );
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping ai-model-invocations-purge cron schedule: %', SQLERRM;
END $$;

NOTIFY pgrst, 'reload schema';
