-- ─── VA EOD reporting + performance tracking with a verification layer ───────
--
-- The design inverts the usual self-reported EOD. The system pre-fills what it
-- already observed (Apploye hours, GHL activity, Airtable jobs/applicants,
-- workspace screening/onboarding, Stripe collections) and the VA only supplies
-- what no source can see. Three tiers of field:
--
--   Tier 1  auto-filled, read-only  — system-fed, a VA can never overwrite it
--   Tier 2  VA-entered, corroborated — compared to a signal on submit
--   Tier 3  qualitative, never scored — blockers, notes, priorities
--
-- Principles enforced by this schema:
--   * va_verified_metrics is SYSTEM-WRITTEN ONLY. Every metric column is
--     NULLABLE and NULL means "unverified" — a source outage must never be
--     recorded as a real zero.
--   * Every metric carries its source + sync timestamp (metric_sources) and
--     every source carries its reachability (source_status).
--   * Re-syncing a day updates in place (unique on va_id + work_date), so a
--     replay can never duplicate a day.
--   * One EOD submission per VA per day (unique on va_id + work_date).
--   * Discrepancies are prompts for human review, never penalties. A flag
--     captures the VA's explanation first; an admin decides the outcome.
--   * Apploye supplies HOURS ONLY. There is deliberately no column anywhere in
--     this schema for screenshots, activity percentages, keystrokes or app
--     usage — that data is never ingested, stored or displayed.
--
-- Reuses: va_onboarding (the VA record), events + discord_routes (alerts),
-- app_settings (thresholds + EOD window), pg_cron + pg_net (scheduled sync),
-- is_admin_or_va() / has_role() RLS.

-- ─── 1. VA record: verification identity + performance profile ───────────────
--
-- Metrics are attributed to a VA through their linked source user IDs. GHL and
-- workspace IDs already live on va_onboarding (ghl_user_id, portal_user_id);
-- Apploye is the only new one, and it reuses the column name and email-match
-- linking convention the cleaner side already established
-- (cleaners.apploye_member_id, see 20260530_apploye_integration.sql).

ALTER TABLE public.va_onboarding
  ADD COLUMN IF NOT EXISTS apploye_member_id text,
  ADD COLUMN IF NOT EXISTS start_date date,
  ADD COLUMN IF NOT EXISTS rate_cents integer,
  ADD COLUMN IF NOT EXISTS functions_assigned text[] NOT NULL DEFAULT '{}',
  -- Performance standing, distinct from the onboarding `status` lifecycle.
  ADD COLUMN IF NOT EXISTS performance_status text NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS perf_airtable_record_id text;

DO $$
BEGIN
  ALTER TABLE public.va_onboarding
    ADD CONSTRAINT va_onboarding_performance_status_check
    CHECK (performance_status IN ('active','probation','inactive','removed'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS va_onboarding_apploye_idx
  ON public.va_onboarding (apploye_member_id) WHERE apploye_member_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS va_onboarding_portal_user_idx
  ON public.va_onboarding (portal_user_id) WHERE portal_user_id IS NOT NULL;

-- ─── 2. va_eod_submissions — one per VA per day ──────────────────────────────

CREATE TABLE IF NOT EXISTS public.va_eod_submissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_number integer GENERATED BY DEFAULT AS IDENTITY,
  va_id uuid NOT NULL REFERENCES public.va_onboarding(id) ON DELETE CASCADE,
  work_date date NOT NULL,

  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft','submitted','reviewed','flagged')),

  -- Which task blocks the VA opened. Drives which question sets rendered and
  -- therefore which Tier 2 fields are meaningful for this day.
  tasks_selected text[] NOT NULL DEFAULT '{}',

  -- Tier 2 ONLY: { metricKey: number }. Tier 1 values are never accepted from
  -- the client — they live exclusively on va_verified_metrics.
  self_reported jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Tier 3, never scored. Free text that is safe to be honest in.
  blockers text,
  priorities text,
  wins text,
  escalations text,
  task_notes jsonb NOT NULL DEFAULT '{}'::jsonb,   -- { taskId: note }

  -- Snapshot of the verified metrics the VA actually saw when submitting, so
  -- a later re-sync can never rewrite the history of what was reviewed.
  verified_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,

  submitted_at timestamptz,
  submitted_late boolean NOT NULL DEFAULT false,
  -- Once locked the day is read-only to the VA (admin window has passed).
  locked_at timestamptz,

  reviewed_by uuid,
  reviewed_by_name text,
  reviewed_at timestamptz,
  review_note text,

  airtable_record_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT va_eod_submissions_one_per_day UNIQUE (va_id, work_date)
);

CREATE INDEX IF NOT EXISTS va_eod_submissions_date_idx
  ON public.va_eod_submissions (work_date DESC);
CREATE INDEX IF NOT EXISTS va_eod_submissions_status_idx
  ON public.va_eod_submissions (status) WHERE status <> 'draft';

-- ─── 3. va_verified_metrics — the source of truth, system-written only ───────
--
-- NULL means UNVERIFIED (source unavailable / not configured / not applicable).
-- 0 means the source was reached and genuinely reported nothing. The two are
-- never conflated: source_status records reachability per source.

CREATE TABLE IF NOT EXISTS public.va_verified_metrics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  va_id uuid NOT NULL REFERENCES public.va_onboarding(id) ON DELETE CASCADE,
  work_date date NOT NULL,

  -- Apploye (hours only — no activity, screenshots or app usage)
  hours_tracked numeric(6,2),

  -- GHL
  calls_placed integer,
  conversations_connected integer,
  sms_sent integer,
  inbound_leads integer,
  leads_responded integer,
  median_response_seconds integer,
  leads_converted integer,

  -- Airtable — Client & Revenue Ops / workspace bookings
  bookings_created integer,
  revenue_booked_cents bigint,
  quotes_sent integer,
  commercial_accounts_touched integer,
  walkthroughs_booked integer,

  -- Stripe
  revenue_collected_cents bigint,

  -- Airtable — Talent Acquisition / workspace cleaner hub
  applications_reviewed integer,
  phone_screens_completed integer,
  screens_advanced integer,
  screens_held integer,
  screens_declined integer,
  onboarding_launched integer,
  cleaners_activated integer,

  -- { source: { status: 'ok'|'unavailable'|'not_configured'|'unlinked',
  --             synced_at: iso, error?: string } }
  source_status jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- { metricKey: { source: string, synced_at: iso, status: string } }
  metric_sources jsonb NOT NULL DEFAULT '{}'::jsonb,

  last_synced_at timestamptz NOT NULL DEFAULT now(),
  airtable_record_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT va_verified_metrics_one_per_day UNIQUE (va_id, work_date)
);

CREATE INDEX IF NOT EXISTS va_verified_metrics_date_idx
  ON public.va_verified_metrics (work_date DESC);

COMMENT ON TABLE public.va_verified_metrics IS
  'System-written source of truth for VA daily metrics. Never hand-edited. NULL = unverified, never a real zero. Apploye contributes hours only — no activity or monitoring data is stored here or anywhere else.';

-- ─── 4. va_discrepancy_flags — a prompt to review, not an accusation ─────────

CREATE TABLE IF NOT EXISTS public.va_discrepancy_flags (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  flag_number integer GENERATED BY DEFAULT AS IDENTITY,
  va_id uuid NOT NULL REFERENCES public.va_onboarding(id) ON DELETE CASCADE,
  work_date date NOT NULL,
  submission_id uuid NOT NULL REFERENCES public.va_eod_submissions(id) ON DELETE CASCADE,

  metric_key text NOT NULL,
  metric_label text,
  self_reported numeric,
  verified numeric,
  variance numeric,
  variance_pct numeric,

  severity text NOT NULL DEFAULT 'low' CHECK (severity IN ('low','medium','high')),
  status text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open','explained','confirmed_issue','dismissed')),

  -- The VA answers first. A human decides after.
  va_explanation text,
  va_explained_at timestamptz,

  review_note text,
  reviewed_by uuid,
  reviewed_by_name text,
  reviewed_at timestamptz,

  -- How many confirmed/open flags for this metric fell inside the rolling
  -- repeat window when this one was raised (drives High severity).
  repeat_count integer NOT NULL DEFAULT 0,

  airtable_record_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  -- Re-submitting the same day re-evaluates in place instead of piling up.
  CONSTRAINT va_discrepancy_flags_one_per_metric UNIQUE (submission_id, metric_key)
);

CREATE INDEX IF NOT EXISTS va_discrepancy_flags_open_idx
  ON public.va_discrepancy_flags (status, work_date DESC) WHERE status = 'open';
CREATE INDEX IF NOT EXISTS va_discrepancy_flags_va_idx
  ON public.va_discrepancy_flags (va_id, work_date DESC);

COMMENT ON TABLE public.va_discrepancy_flags IS
  'Variance between a Tier 2 self-reported value and its corroborating signal. A flag asks for an explanation and routes to a human — it never auto-penalizes and never affects pay.';

-- ─── 5. va_kpi_targets ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.va_kpi_targets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  target_number integer GENERATED BY DEFAULT AS IDENTITY,
  -- Role-wide when va_id is NULL; 'all' applies to every function.
  function text NOT NULL DEFAULT 'all'
    CHECK (function IN ('all','operations','sales','recruiting')),
  metric_key text NOT NULL,
  label text NOT NULL,
  target_value numeric NOT NULL,
  -- gte: hit the target or above (calls/day). lte: stay at or below (minutes
  -- to first response, submission time).
  comparator text NOT NULL DEFAULT 'gte' CHECK (comparator IN ('gte','lte')),
  unit text,
  period text NOT NULL DEFAULT 'daily' CHECK (period IN ('daily','weekly','monthly')),
  va_id uuid REFERENCES public.va_onboarding(id) ON DELETE CASCADE,
  active boolean NOT NULL DEFAULT true,
  effective_date date NOT NULL DEFAULT CURRENT_DATE,
  airtable_record_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS va_kpi_targets_scope_uniq
  ON public.va_kpi_targets (metric_key, period, function, COALESCE(va_id, '00000000-0000-0000-0000-000000000000'::uuid), effective_date);

-- Seed the existing VA KPIs.
INSERT INTO public.va_kpi_targets (function, metric_key, label, target_value, comparator, unit, period)
VALUES
  ('all',        'median_response_seconds', 'Median first-response time',   300, 'lte', 'seconds', 'daily'),
  ('sales',      'calls_placed',            'Outbound calls per day',        30, 'gte', 'calls',   'daily'),
  ('recruiting', 'applications_reviewed',   'Applications reviewed per day',  5, 'gte', 'apps',    'daily'),
  ('recruiting', 'phone_screens_completed', 'Phone screens per day',          2, 'gte', 'screens', 'daily'),
  ('all',        'eod_submitted_by',        'EOD submitted by 5:30 PM',    1050, 'lte', 'minutes past midnight', 'daily')
ON CONFLICT DO NOTHING;

-- ─── 6. va_performance_periods ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.va_performance_periods (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  period_number integer GENERATED BY DEFAULT AS IDENTITY,
  va_id uuid NOT NULL REFERENCES public.va_onboarding(id) ON DELETE CASCADE,
  period_type text NOT NULL CHECK (period_type IN ('weekly','monthly')),
  start_date date NOT NULL,
  end_date date NOT NULL,

  total_hours numeric(8,2),
  -- { metricKey: number|null } — summed verified metrics for the window.
  rollups jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- { metricKey: { target, actual, attainment_pct, met } }
  target_detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  target_attainment_pct numeric(6,2),

  revenue_attributed_cents bigint,
  -- The single number that answers whether the VA pays for themselves.
  revenue_per_hour_cents bigint,

  eod_expected_days integer,
  eod_submitted_days integer,
  eod_late_days integer,
  eod_compliance_pct numeric(6,2),
  discrepancy_count integer NOT NULL DEFAULT 0,

  overall_rating text CHECK (overall_rating IN ('exceeding','on_track','needs_improvement','at_risk')),
  reviewed_by uuid,
  reviewed_by_name text,
  reviewed_at timestamptz,
  review_notes text,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','reviewed','final')),

  airtable_record_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT va_performance_periods_uniq UNIQUE (va_id, period_type, start_date)
);

-- ─── 7. va_coaching_log ──────────────────────────────────────────────────────
--
-- The documented ladder: coaching conversation → formal warning. Never a pay
-- consequence — consistent with 1099 contractor treatment.

CREATE TABLE IF NOT EXISTS public.va_coaching_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entry_number integer GENERATED BY DEFAULT AS IDENTITY,
  va_id uuid NOT NULL REFERENCES public.va_onboarding(id) ON DELETE CASCADE,
  entry_date date NOT NULL DEFAULT CURRENT_DATE,
  entry_type text NOT NULL
    CHECK (entry_type IN ('coaching_note','formal_warning','recognition','performance_review')),

  trigger_flag_id uuid REFERENCES public.va_discrepancy_flags(id) ON DELETE SET NULL,
  trigger_period_id uuid REFERENCES public.va_performance_periods(id) ON DELETE SET NULL,

  summary text NOT NULL,
  action_agreed text,
  follow_up_date date,
  logged_by uuid,
  logged_by_name text,
  outcome text,

  airtable_record_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS va_coaching_log_va_idx
  ON public.va_coaching_log (va_id, entry_date DESC);

-- ─── updated_at triggers ─────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.va_perf_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'va_eod_submissions','va_verified_metrics','va_discrepancy_flags',
    'va_kpi_targets','va_performance_periods','va_coaching_log'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_touch ON public.%I', t, t);
    EXECUTE format(
      'CREATE TRIGGER trg_%s_touch BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.va_perf_touch_updated_at()',
      t, t
    );
  END LOOP;
END $$;

-- ─── RLS ─────────────────────────────────────────────────────────────────────
--
-- Read access is ADMIN-ONLY, deliberately. Qualitative fields (blockers, notes,
-- escalations) only stay safe to be honest in if they aren't visible to peers,
-- and the VA Performance tab is an admin surface. VAs reach their OWN day
-- exclusively through /api/va/eod, which verifies identity and then uses the
-- service role scoped to that one row.

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'va_eod_submissions','va_verified_metrics','va_discrepancy_flags',
    'va_kpi_targets','va_performance_periods','va_coaching_log'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_admin_all', t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING (public.has_role(auth.uid(), ''admin'')) WITH CHECK (public.has_role(auth.uid(), ''admin''))',
      t || '_admin_all', t
    );
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_service_role', t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)',
      t || '_service_role', t
    );
  END LOOP;
END $$;

-- va_verified_metrics is system-written: strip UPDATE/INSERT from the admin
-- policy so nobody can hand-edit the source of truth from the console.
DROP POLICY IF EXISTS va_verified_metrics_admin_all ON public.va_verified_metrics;
DROP POLICY IF EXISTS va_verified_metrics_admin_read ON public.va_verified_metrics;
CREATE POLICY va_verified_metrics_admin_read ON public.va_verified_metrics
  FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

-- ─── Settings (admin-configurable) ───────────────────────────────────────────

INSERT INTO public.app_settings (key, value, description)
VALUES
  (
    'va_eod_settings',
    jsonb_build_object(
      'timezone', 'America/New_York',
      -- How many days back a VA may still open/edit. 1 = today + yesterday.
      'backdate_days', 1,
      -- On-time cutoff, local. Submissions after this are marked late.
      'cutoff_local_time', '17:30',
      -- Hours after the work date before the submission locks to the VA.
      'lock_after_hours', 36
    ),
    'EOD form window: timezone, how far back a VA may backdate, the on-time cutoff, and when a day locks.'
  ),
  (
    'va_discrepancy_thresholds',
    jsonb_build_object(
      -- Flag when the variance exceeds the GREATER of pct-of-verified or abs.
      'base',   jsonb_build_object('pct', 20, 'abs', 10),
      'medium', jsonb_build_object('pct', 40, 'abs', 25),
      'high',   jsonb_build_object('pct', 75, 'abs', 50),
      -- A repeat inside the rolling window escalates to High.
      'repeat', jsonb_build_object('window_days', 14, 'count', 3)
    ),
    'Variance thresholds for Tier 2 discrepancy detection. A flag is a prompt for human review — never an automatic penalty.'
  )
ON CONFLICT (key) DO NOTHING;

-- ─── Discord routing for the new events ──────────────────────────────────────

INSERT INTO public.discord_routes (event_type, webhook_key, role_keys, enabled)
VALUES
  ('va.eod.submitted',        'DISCORD_WEBHOOK_CLEANERS', ARRAY['DISCORD_ROLE_OPERATIONS'], true),
  ('va.discrepancy.flagged',  'DISCORD_WEBHOOK_CLEANERS', ARRAY['DISCORD_ROLE_OPERATIONS'], true),
  ('va.discrepancy.reviewed', 'DISCORD_WEBHOOK_CLEANERS', ARRAY['DISCORD_ROLE_OPERATIONS'], true),
  ('va.coaching.logged',      'DISCORD_WEBHOOK_CLEANERS', ARRAY['DISCORD_ROLE_OPERATIONS'], true)
ON CONFLICT (event_type) DO NOTHING;

-- ─── Scheduled verification sync ─────────────────────────────────────────────
--
-- Metrics are pulled through the day so the form pre-fills with current data,
-- and again after the EOD cutoff to settle the day. Idempotent: each run
-- upserts on (va_id, work_date).

-- APPLOYE_API_KEY and the Airtable PAT already exist in app_secrets and are
-- deliberately not touched here. Only the two new keys are seeded.
INSERT INTO public.app_secrets (key, value, description)
VALUES
  ('VA_METRICS_SYNC_URL', 'https://admin.novaracleaning.com/api/va/performance/sync',
   'Next.js route that pulls verified VA metrics from Apploye/GHL/Airtable/workspace/Stripe.'),
  ('VA_METRICS_SYNC_SECRET', encode(gen_random_bytes(24), 'hex'),
   'Shared secret for the VA metrics sync route (query ?secret= or x-va-metrics-secret header).'),
  ('AIRTABLE_TEAM_PERF_BASE_ID', '',
   'Airtable base id for "Novara — Team Performance". Set automatically the first time the base is provisioned.'),
  ('AIRTABLE_WORKSPACE_ID', '',
   'Airtable workspace id (wsp…) — required once, to create the Team Performance base via the Meta API.')
ON CONFLICT (key) DO NOTHING;

-- Correct the Apploye descriptions seeded by 20260530_apploye_integration.sql.
-- They describe a Bearer token against www.apploye.com/api/v1, but the client
-- that was actually built (supabase/functions/_shared/apploye-client.ts) uses
-- the public API with an X-APPLOYE-API-KEY header — verified against the live
-- endpoint. APPLOYE_WORKSPACE_ID is unused by that API and is left in place
-- only so an operator doesn't wonder where it went.
UPDATE public.app_secrets SET description =
  'Apploye Organization API Key, sent as the X-APPLOYE-API-KEY header. Used for /members and /timesheets ONLY — identity and hours. Screenshots and activity data are never requested or stored.'
WHERE key = 'APPLOYE_API_KEY';

UPDATE public.app_secrets SET description =
  'Optional override of the Apploye API base URL. Defaults to https://public-api.apploye.com when blank.'
WHERE key = 'APPLOYE_API_BASE';

UPDATE public.app_secrets SET description =
  'UNUSED — the Apploye public API scopes by the organization API key, so no workspace id is sent. Kept to avoid confusion; safe to delete.'
WHERE key = 'APPLOYE_WORKSPACE_ID';

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule('va-metrics-sync-hourly') WHERE EXISTS (
      SELECT 1 FROM cron.job WHERE jobname = 'va-metrics-sync-hourly'
    );
    PERFORM cron.schedule(
      'va-metrics-sync-hourly',
      -- Every hour 12:00–02:00 UTC (roughly 8am–9pm America/New_York), so the
      -- form always pre-fills with current data and the post-cutoff run
      -- settles the day.
      '10 0-2,12-23 * * *',
      $CRON$
        SELECT net.http_post(
          url := (SELECT value FROM public.app_secrets WHERE key = 'VA_METRICS_SYNC_URL')
                 || '?secret=' || (SELECT value FROM public.app_secrets WHERE key = 'VA_METRICS_SYNC_SECRET'),
          headers := jsonb_build_object('Content-Type', 'application/json'),
          body := jsonb_build_object('scope', 'today', 'source', 'pg_cron'),
          timeout_milliseconds := 120000
        )
        WHERE COALESCE((SELECT value FROM public.app_secrets WHERE key = 'VA_METRICS_SYNC_URL'), '') <> '';
      $CRON$
    );
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
